
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'AcusticCheck': typeof import("../components/AcusticCheck.vue")['default']
    'AudioReactiveBar': typeof import("../components/AudioReactiveBar.vue")['default']
    'BootomBar': typeof import("../components/BootomBar.vue")['default']
    'PlayerNodes': typeof import("../components/Player/Nodes")['default']
    'Player': typeof import("../components/Player/Player")['default']
    'ChartConfig': typeof import("../components/chartConfig")['default']
    'ExperimentsAudioElement': typeof import("../components/experiments/AudioElement.vue")['default']
    'ExperimentsAudioElement2': typeof import("../components/experiments/AudioElement2.vue")['default']
    'ExperimentsAudioElementManager': typeof import("../components/experiments/AudioElementManager.vue")['default']
    'ExperimentsAudioNoiseTest': typeof import("../components/experiments/AudioNoiseTest.vue")['default']
    'ExperimentsAudioNoiseTest2': typeof import("../components/experiments/AudioNoiseTest2.vue")['default']
    'ExperimentsAudioVisualization': typeof import("../components/experiments/AudioVisualization.vue")['default']
    'ExperimentsHomepagesMusicGainForest': typeof import("../components/experiments/homepages/MusicGainForest.vue")['default']
    'ExperimentsHomepagesMusicGainLagoon': typeof import("../components/experiments/homepages/MusicGainLagoon.vue")['default']
    'ExperimentsHomepagesMusicGainMeadow': typeof import("../components/experiments/homepages/MusicGainMeadow.vue")['default']
    'ExperimentsHomepagesMusicGainTropic': typeof import("../components/experiments/homepages/MusicGainTropic.vue")['default']
    'ExperimentsHomepagesNoiseMusicGainForest': typeof import("../components/experiments/homepages/NoiseMusicGainForest.vue")['default']
    'ExperimentsHomepagesNoiseMusicGainLagoon': typeof import("../components/experiments/homepages/NoiseMusicGainLagoon.vue")['default']
    'ExperimentsHomepagesNoiseMusicGainMeadow': typeof import("../components/experiments/homepages/NoiseMusicGainMeadow.vue")['default']
    'ExperimentsHomepagesNoiseMusicGainTropics': typeof import("../components/experiments/homepages/NoiseMusicGainTropics.vue")['default']
    'ExperimentsHomepagesRNBODevice': typeof import("../components/experiments/homepages/RNBODevice.vue")['default']
    'ExperimentsHomepagesOldNoiseMusicGainLagoon': typeof import("../components/experiments/homepages/old_NoiseMusicGainLagoon.vue")['default']
    'ExperimentsHomepagesOldNoiseMusicGainMeadow': typeof import("../components/experiments/homepages/old_NoiseMusicGainMeadow.vue")['default']
    'ExperimentsHomepagesOldNoiseMusicGainMeadowAudioElement2': typeof import("../components/experiments/homepages/old_NoiseMusicGainMeadowAudioElement2.vue")['default']
    'ExperimentsHomepagesOldNoiseMusicGainTropics': typeof import("../components/experiments/homepages/old_NoiseMusicGainTropics.vue")['default']
    'ExperimentsSpotifyPomodoroPlaylist': typeof import("../components/experiments/spotify/PomodoroPlaylist.vue")['default']
    'ExperimentsSpotify': typeof import("../components/experiments/spotify/Spotify.vue")['default']
    'ExperimentsSpotifyEmbed': typeof import("../components/experiments/spotify/SpotifyEmbed.vue")['default']
    'ExperimentsStatemanagementStateBar': typeof import("../components/experiments/statemanagement/StateBar.vue")['default']
    'ExperimentsTestsAlgorithmusTests': typeof import("../components/experiments/tests/AlgorithmusTests")['default']
    'ExperimentsTestsMicNoisePatchMusic2': typeof import("../components/experiments/tests/MicNoisePatchMusic2.vue")['default']
    'ExperimentsTestsMicrophone': typeof import("../components/experiments/tests/Microphone.vue")['default']
    'ExperimentsTestsNoiseMusicGain': typeof import("../components/experiments/tests/NoiseMusicGain.vue")['default']
    'ExperimentsTestsNoiseMusicGainFadeIn': typeof import("../components/experiments/tests/NoiseMusicGainFadeIn.vue")['default']
    'ExperimentsTestsNoiseMusicGainMic': typeof import("../components/experiments/tests/NoiseMusicGainMic.vue")['default']
    'ExperimentsTestsNoiseMusicGainPlayPause': typeof import("../components/experiments/tests/NoiseMusicGainPlayPause.vue")['default']
    'ExperimentsTestsNoiseMusicGainPlayPauseDevice': typeof import("../components/experiments/tests/NoiseMusicGainPlayPauseDevice.vue")['default']
    'ExperimentsTestsNoiseMusicWebAudio': typeof import("../components/experiments/tests/NoiseMusicWebAudio.vue")['default']
    'ExperimentsTestsShowcasesNoisePatchMusicGlitchOnLoad': typeof import("../components/experiments/tests/showcases/NoisePatchMusic_glitchOnLoad.vue")['default']
    'ExperimentsTestsShowcasesPlayer': typeof import("../components/experiments/tests/showcases/Player.vue")['default']
    'ExperimentsTestsShowcasesRNBOPlayer': typeof import("../components/experiments/tests/showcases/RNBOPlayer.vue")['default']
    'Homebar': typeof import("../components/homebar.vue")['default']
    'SvgHomebarWaveSVG': typeof import("../components/svg/homebar/WaveSVG.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'NuxtLinkLocale': typeof import("../node_modules/.pnpm/@nuxtjs+i18n@8.5.5_magicast@0.3.5_rollup@4.24.0_vue@3.5.11_typescript@5.6.3__webpack-sources@3.2.3/node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
    'SwitchLocalePathLink': typeof import("../node_modules/.pnpm/@nuxtjs+i18n@8.5.5_magicast@0.3.5_rollup@4.24.0_vue@3.5.11_typescript@5.6.3__webpack-sources@3.2.3/node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
    'NuxtPage': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyAcusticCheck': typeof import("../components/AcusticCheck.vue")['default']
    'LazyAudioReactiveBar': typeof import("../components/AudioReactiveBar.vue")['default']
    'LazyBootomBar': typeof import("../components/BootomBar.vue")['default']
    'LazyPlayerNodes': typeof import("../components/Player/Nodes")['default']
    'LazyPlayer': typeof import("../components/Player/Player")['default']
    'LazyChartConfig': typeof import("../components/chartConfig")['default']
    'LazyExperimentsAudioElement': typeof import("../components/experiments/AudioElement.vue")['default']
    'LazyExperimentsAudioElement2': typeof import("../components/experiments/AudioElement2.vue")['default']
    'LazyExperimentsAudioElementManager': typeof import("../components/experiments/AudioElementManager.vue")['default']
    'LazyExperimentsAudioNoiseTest': typeof import("../components/experiments/AudioNoiseTest.vue")['default']
    'LazyExperimentsAudioNoiseTest2': typeof import("../components/experiments/AudioNoiseTest2.vue")['default']
    'LazyExperimentsAudioVisualization': typeof import("../components/experiments/AudioVisualization.vue")['default']
    'LazyExperimentsHomepagesMusicGainForest': typeof import("../components/experiments/homepages/MusicGainForest.vue")['default']
    'LazyExperimentsHomepagesMusicGainLagoon': typeof import("../components/experiments/homepages/MusicGainLagoon.vue")['default']
    'LazyExperimentsHomepagesMusicGainMeadow': typeof import("../components/experiments/homepages/MusicGainMeadow.vue")['default']
    'LazyExperimentsHomepagesMusicGainTropic': typeof import("../components/experiments/homepages/MusicGainTropic.vue")['default']
    'LazyExperimentsHomepagesNoiseMusicGainForest': typeof import("../components/experiments/homepages/NoiseMusicGainForest.vue")['default']
    'LazyExperimentsHomepagesNoiseMusicGainLagoon': typeof import("../components/experiments/homepages/NoiseMusicGainLagoon.vue")['default']
    'LazyExperimentsHomepagesNoiseMusicGainMeadow': typeof import("../components/experiments/homepages/NoiseMusicGainMeadow.vue")['default']
    'LazyExperimentsHomepagesNoiseMusicGainTropics': typeof import("../components/experiments/homepages/NoiseMusicGainTropics.vue")['default']
    'LazyExperimentsHomepagesRNBODevice': typeof import("../components/experiments/homepages/RNBODevice.vue")['default']
    'LazyExperimentsHomepagesOldNoiseMusicGainLagoon': typeof import("../components/experiments/homepages/old_NoiseMusicGainLagoon.vue")['default']
    'LazyExperimentsHomepagesOldNoiseMusicGainMeadow': typeof import("../components/experiments/homepages/old_NoiseMusicGainMeadow.vue")['default']
    'LazyExperimentsHomepagesOldNoiseMusicGainMeadowAudioElement2': typeof import("../components/experiments/homepages/old_NoiseMusicGainMeadowAudioElement2.vue")['default']
    'LazyExperimentsHomepagesOldNoiseMusicGainTropics': typeof import("../components/experiments/homepages/old_NoiseMusicGainTropics.vue")['default']
    'LazyExperimentsSpotifyPomodoroPlaylist': typeof import("../components/experiments/spotify/PomodoroPlaylist.vue")['default']
    'LazyExperimentsSpotify': typeof import("../components/experiments/spotify/Spotify.vue")['default']
    'LazyExperimentsSpotifyEmbed': typeof import("../components/experiments/spotify/SpotifyEmbed.vue")['default']
    'LazyExperimentsStatemanagementStateBar': typeof import("../components/experiments/statemanagement/StateBar.vue")['default']
    'LazyExperimentsTestsAlgorithmusTests': typeof import("../components/experiments/tests/AlgorithmusTests")['default']
    'LazyExperimentsTestsMicNoisePatchMusic2': typeof import("../components/experiments/tests/MicNoisePatchMusic2.vue")['default']
    'LazyExperimentsTestsMicrophone': typeof import("../components/experiments/tests/Microphone.vue")['default']
    'LazyExperimentsTestsNoiseMusicGain': typeof import("../components/experiments/tests/NoiseMusicGain.vue")['default']
    'LazyExperimentsTestsNoiseMusicGainFadeIn': typeof import("../components/experiments/tests/NoiseMusicGainFadeIn.vue")['default']
    'LazyExperimentsTestsNoiseMusicGainMic': typeof import("../components/experiments/tests/NoiseMusicGainMic.vue")['default']
    'LazyExperimentsTestsNoiseMusicGainPlayPause': typeof import("../components/experiments/tests/NoiseMusicGainPlayPause.vue")['default']
    'LazyExperimentsTestsNoiseMusicGainPlayPauseDevice': typeof import("../components/experiments/tests/NoiseMusicGainPlayPauseDevice.vue")['default']
    'LazyExperimentsTestsNoiseMusicWebAudio': typeof import("../components/experiments/tests/NoiseMusicWebAudio.vue")['default']
    'LazyExperimentsTestsShowcasesNoisePatchMusicGlitchOnLoad': typeof import("../components/experiments/tests/showcases/NoisePatchMusic_glitchOnLoad.vue")['default']
    'LazyExperimentsTestsShowcasesPlayer': typeof import("../components/experiments/tests/showcases/Player.vue")['default']
    'LazyExperimentsTestsShowcasesRNBOPlayer': typeof import("../components/experiments/tests/showcases/RNBOPlayer.vue")['default']
    'LazyHomebar': typeof import("../components/homebar.vue")['default']
    'LazySvgHomebarWaveSVG': typeof import("../components/svg/homebar/WaveSVG.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyNuxtLinkLocale': typeof import("../node_modules/.pnpm/@nuxtjs+i18n@8.5.5_magicast@0.3.5_rollup@4.24.0_vue@3.5.11_typescript@5.6.3__webpack-sources@3.2.3/node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
    'LazySwitchLocalePathLink': typeof import("../node_modules/.pnpm/@nuxtjs+i18n@8.5.5_magicast@0.3.5_rollup@4.24.0_vue@3.5.11_typescript@5.6.3__webpack-sources@3.2.3/node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
    'LazyNuxtPage': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const AcusticCheck: typeof import("../components/AcusticCheck.vue")['default']
export const AudioReactiveBar: typeof import("../components/AudioReactiveBar.vue")['default']
export const BootomBar: typeof import("../components/BootomBar.vue")['default']
export const PlayerNodes: typeof import("../components/Player/Nodes")['default']
export const Player: typeof import("../components/Player/Player")['default']
export const ChartConfig: typeof import("../components/chartConfig")['default']
export const ExperimentsAudioElement: typeof import("../components/experiments/AudioElement.vue")['default']
export const ExperimentsAudioElement2: typeof import("../components/experiments/AudioElement2.vue")['default']
export const ExperimentsAudioElementManager: typeof import("../components/experiments/AudioElementManager.vue")['default']
export const ExperimentsAudioNoiseTest: typeof import("../components/experiments/AudioNoiseTest.vue")['default']
export const ExperimentsAudioNoiseTest2: typeof import("../components/experiments/AudioNoiseTest2.vue")['default']
export const ExperimentsAudioVisualization: typeof import("../components/experiments/AudioVisualization.vue")['default']
export const ExperimentsHomepagesMusicGainForest: typeof import("../components/experiments/homepages/MusicGainForest.vue")['default']
export const ExperimentsHomepagesMusicGainLagoon: typeof import("../components/experiments/homepages/MusicGainLagoon.vue")['default']
export const ExperimentsHomepagesMusicGainMeadow: typeof import("../components/experiments/homepages/MusicGainMeadow.vue")['default']
export const ExperimentsHomepagesMusicGainTropic: typeof import("../components/experiments/homepages/MusicGainTropic.vue")['default']
export const ExperimentsHomepagesNoiseMusicGainForest: typeof import("../components/experiments/homepages/NoiseMusicGainForest.vue")['default']
export const ExperimentsHomepagesNoiseMusicGainLagoon: typeof import("../components/experiments/homepages/NoiseMusicGainLagoon.vue")['default']
export const ExperimentsHomepagesNoiseMusicGainMeadow: typeof import("../components/experiments/homepages/NoiseMusicGainMeadow.vue")['default']
export const ExperimentsHomepagesNoiseMusicGainTropics: typeof import("../components/experiments/homepages/NoiseMusicGainTropics.vue")['default']
export const ExperimentsHomepagesRNBODevice: typeof import("../components/experiments/homepages/RNBODevice.vue")['default']
export const ExperimentsHomepagesOldNoiseMusicGainLagoon: typeof import("../components/experiments/homepages/old_NoiseMusicGainLagoon.vue")['default']
export const ExperimentsHomepagesOldNoiseMusicGainMeadow: typeof import("../components/experiments/homepages/old_NoiseMusicGainMeadow.vue")['default']
export const ExperimentsHomepagesOldNoiseMusicGainMeadowAudioElement2: typeof import("../components/experiments/homepages/old_NoiseMusicGainMeadowAudioElement2.vue")['default']
export const ExperimentsHomepagesOldNoiseMusicGainTropics: typeof import("../components/experiments/homepages/old_NoiseMusicGainTropics.vue")['default']
export const ExperimentsSpotifyPomodoroPlaylist: typeof import("../components/experiments/spotify/PomodoroPlaylist.vue")['default']
export const ExperimentsSpotify: typeof import("../components/experiments/spotify/Spotify.vue")['default']
export const ExperimentsSpotifyEmbed: typeof import("../components/experiments/spotify/SpotifyEmbed.vue")['default']
export const ExperimentsStatemanagementStateBar: typeof import("../components/experiments/statemanagement/StateBar.vue")['default']
export const ExperimentsTestsAlgorithmusTests: typeof import("../components/experiments/tests/AlgorithmusTests")['default']
export const ExperimentsTestsMicNoisePatchMusic2: typeof import("../components/experiments/tests/MicNoisePatchMusic2.vue")['default']
export const ExperimentsTestsMicrophone: typeof import("../components/experiments/tests/Microphone.vue")['default']
export const ExperimentsTestsNoiseMusicGain: typeof import("../components/experiments/tests/NoiseMusicGain.vue")['default']
export const ExperimentsTestsNoiseMusicGainFadeIn: typeof import("../components/experiments/tests/NoiseMusicGainFadeIn.vue")['default']
export const ExperimentsTestsNoiseMusicGainMic: typeof import("../components/experiments/tests/NoiseMusicGainMic.vue")['default']
export const ExperimentsTestsNoiseMusicGainPlayPause: typeof import("../components/experiments/tests/NoiseMusicGainPlayPause.vue")['default']
export const ExperimentsTestsNoiseMusicGainPlayPauseDevice: typeof import("../components/experiments/tests/NoiseMusicGainPlayPauseDevice.vue")['default']
export const ExperimentsTestsNoiseMusicWebAudio: typeof import("../components/experiments/tests/NoiseMusicWebAudio.vue")['default']
export const ExperimentsTestsShowcasesNoisePatchMusicGlitchOnLoad: typeof import("../components/experiments/tests/showcases/NoisePatchMusic_glitchOnLoad.vue")['default']
export const ExperimentsTestsShowcasesPlayer: typeof import("../components/experiments/tests/showcases/Player.vue")['default']
export const ExperimentsTestsShowcasesRNBOPlayer: typeof import("../components/experiments/tests/showcases/RNBOPlayer.vue")['default']
export const Homebar: typeof import("../components/homebar.vue")['default']
export const SvgHomebarWaveSVG: typeof import("../components/svg/homebar/WaveSVG.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const NuxtLinkLocale: typeof import("../node_modules/.pnpm/@nuxtjs+i18n@8.5.5_magicast@0.3.5_rollup@4.24.0_vue@3.5.11_typescript@5.6.3__webpack-sources@3.2.3/node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
export const SwitchLocalePathLink: typeof import("../node_modules/.pnpm/@nuxtjs+i18n@8.5.5_magicast@0.3.5_rollup@4.24.0_vue@3.5.11_typescript@5.6.3__webpack-sources@3.2.3/node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
export const NuxtPage: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyAcusticCheck: typeof import("../components/AcusticCheck.vue")['default']
export const LazyAudioReactiveBar: typeof import("../components/AudioReactiveBar.vue")['default']
export const LazyBootomBar: typeof import("../components/BootomBar.vue")['default']
export const LazyPlayerNodes: typeof import("../components/Player/Nodes")['default']
export const LazyPlayer: typeof import("../components/Player/Player")['default']
export const LazyChartConfig: typeof import("../components/chartConfig")['default']
export const LazyExperimentsAudioElement: typeof import("../components/experiments/AudioElement.vue")['default']
export const LazyExperimentsAudioElement2: typeof import("../components/experiments/AudioElement2.vue")['default']
export const LazyExperimentsAudioElementManager: typeof import("../components/experiments/AudioElementManager.vue")['default']
export const LazyExperimentsAudioNoiseTest: typeof import("../components/experiments/AudioNoiseTest.vue")['default']
export const LazyExperimentsAudioNoiseTest2: typeof import("../components/experiments/AudioNoiseTest2.vue")['default']
export const LazyExperimentsAudioVisualization: typeof import("../components/experiments/AudioVisualization.vue")['default']
export const LazyExperimentsHomepagesMusicGainForest: typeof import("../components/experiments/homepages/MusicGainForest.vue")['default']
export const LazyExperimentsHomepagesMusicGainLagoon: typeof import("../components/experiments/homepages/MusicGainLagoon.vue")['default']
export const LazyExperimentsHomepagesMusicGainMeadow: typeof import("../components/experiments/homepages/MusicGainMeadow.vue")['default']
export const LazyExperimentsHomepagesMusicGainTropic: typeof import("../components/experiments/homepages/MusicGainTropic.vue")['default']
export const LazyExperimentsHomepagesNoiseMusicGainForest: typeof import("../components/experiments/homepages/NoiseMusicGainForest.vue")['default']
export const LazyExperimentsHomepagesNoiseMusicGainLagoon: typeof import("../components/experiments/homepages/NoiseMusicGainLagoon.vue")['default']
export const LazyExperimentsHomepagesNoiseMusicGainMeadow: typeof import("../components/experiments/homepages/NoiseMusicGainMeadow.vue")['default']
export const LazyExperimentsHomepagesNoiseMusicGainTropics: typeof import("../components/experiments/homepages/NoiseMusicGainTropics.vue")['default']
export const LazyExperimentsHomepagesRNBODevice: typeof import("../components/experiments/homepages/RNBODevice.vue")['default']
export const LazyExperimentsHomepagesOldNoiseMusicGainLagoon: typeof import("../components/experiments/homepages/old_NoiseMusicGainLagoon.vue")['default']
export const LazyExperimentsHomepagesOldNoiseMusicGainMeadow: typeof import("../components/experiments/homepages/old_NoiseMusicGainMeadow.vue")['default']
export const LazyExperimentsHomepagesOldNoiseMusicGainMeadowAudioElement2: typeof import("../components/experiments/homepages/old_NoiseMusicGainMeadowAudioElement2.vue")['default']
export const LazyExperimentsHomepagesOldNoiseMusicGainTropics: typeof import("../components/experiments/homepages/old_NoiseMusicGainTropics.vue")['default']
export const LazyExperimentsSpotifyPomodoroPlaylist: typeof import("../components/experiments/spotify/PomodoroPlaylist.vue")['default']
export const LazyExperimentsSpotify: typeof import("../components/experiments/spotify/Spotify.vue")['default']
export const LazyExperimentsSpotifyEmbed: typeof import("../components/experiments/spotify/SpotifyEmbed.vue")['default']
export const LazyExperimentsStatemanagementStateBar: typeof import("../components/experiments/statemanagement/StateBar.vue")['default']
export const LazyExperimentsTestsAlgorithmusTests: typeof import("../components/experiments/tests/AlgorithmusTests")['default']
export const LazyExperimentsTestsMicNoisePatchMusic2: typeof import("../components/experiments/tests/MicNoisePatchMusic2.vue")['default']
export const LazyExperimentsTestsMicrophone: typeof import("../components/experiments/tests/Microphone.vue")['default']
export const LazyExperimentsTestsNoiseMusicGain: typeof import("../components/experiments/tests/NoiseMusicGain.vue")['default']
export const LazyExperimentsTestsNoiseMusicGainFadeIn: typeof import("../components/experiments/tests/NoiseMusicGainFadeIn.vue")['default']
export const LazyExperimentsTestsNoiseMusicGainMic: typeof import("../components/experiments/tests/NoiseMusicGainMic.vue")['default']
export const LazyExperimentsTestsNoiseMusicGainPlayPause: typeof import("../components/experiments/tests/NoiseMusicGainPlayPause.vue")['default']
export const LazyExperimentsTestsNoiseMusicGainPlayPauseDevice: typeof import("../components/experiments/tests/NoiseMusicGainPlayPauseDevice.vue")['default']
export const LazyExperimentsTestsNoiseMusicWebAudio: typeof import("../components/experiments/tests/NoiseMusicWebAudio.vue")['default']
export const LazyExperimentsTestsShowcasesNoisePatchMusicGlitchOnLoad: typeof import("../components/experiments/tests/showcases/NoisePatchMusic_glitchOnLoad.vue")['default']
export const LazyExperimentsTestsShowcasesPlayer: typeof import("../components/experiments/tests/showcases/Player.vue")['default']
export const LazyExperimentsTestsShowcasesRNBOPlayer: typeof import("../components/experiments/tests/showcases/RNBOPlayer.vue")['default']
export const LazyHomebar: typeof import("../components/homebar.vue")['default']
export const LazySvgHomebarWaveSVG: typeof import("../components/svg/homebar/WaveSVG.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyNuxtLinkLocale: typeof import("../node_modules/.pnpm/@nuxtjs+i18n@8.5.5_magicast@0.3.5_rollup@4.24.0_vue@3.5.11_typescript@5.6.3__webpack-sources@3.2.3/node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
export const LazySwitchLocalePathLink: typeof import("../node_modules/.pnpm/@nuxtjs+i18n@8.5.5_magicast@0.3.5_rollup@4.24.0_vue@3.5.11_typescript@5.6.3__webpack-sources@3.2.3/node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
export const LazyNuxtPage: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@8.57.1_ioredis@5.4.1_magicast@0.3_qeaore4mp3y7lt5eyvaat2qqoq/node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
